# Generated by Django 3.1.3 on 2021-02-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='number',
        ),
        migrations.AddField(
            model_name='categoryinround',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
