# Generated by Django 3.1.3 on 2021-02-13 01:16

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='num_of_player',
            new_name='num_of_players',
        ),
        migrations.RemoveField(
            model_name='config',
            name='letter',
        ),
        migrations.AddField(
            model_name='config',
            name='letters',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], default='A', max_length=53),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='num_of_rounds',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=7),
        ),
    ]
