# Generated by Django 3.1.3 on 2021-03-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210302_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='time_per_round',
            field=models.IntegerField(default=120),
        ),
    ]
