# Generated by Django 3.1.3 on 2021-02-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210213_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='game',
            new_name='game_code',
        ),
    ]
