# Generated by Django 3.1.3 on 2021-02-14 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210214_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='game_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
    ]
