# Generated by Django 3.1.3 on 2022-09-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_config_time_per_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
