# Generated by Django 3.1.3 on 2021-02-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210214_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='num_of_cat_per_round',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
