# Generated by Django 3.1.3 on 2021-02-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20210214_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_host',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
