# Generated by Django 3.1.3 on 2021-02-15 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_player_is_host'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Global_Category',
        ),
    ]
