# Generated by Django 3.1.3 on 2021-02-15 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20210215_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='game_code',
            new_name='game',
        ),
        migrations.CreateModel(
            name='Local_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
