# Generated by Django 3.1.3 on 2021-02-15 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20210215_0306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Global_Category',
            new_name='GlobalCategory',
        ),
        migrations.RenameModel(
            old_name='Local_Category',
            new_name='LocalCategory',
        ),
    ]
