# Generated by Django 3.1.3 on 2021-02-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_categoryinround_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='letter',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
    ]
