# Generated by Django 3.1.3 on 2021-02-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20210215_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_played',
            field=models.BooleanField(default=False),
        ),
    ]
