# Generated by Django 3.1.3 on 2021-02-18 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_playeranswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playeranswer',
            old_name='category_num',
            new_name='number',
        ),
    ]
